export const initialVegetables = [
    { id: 1, name: 'Tamatar', defaultQty: '2kg' },
    { id: 2, name: 'Pyaaz', defaultQty: '3kg' },
    { id: 3, name: 'Aloo', defaultQty: '2kg' },
    { id: 4, name: 'Kakdi', defaultQty: '1kg' },
    { id: 18, name: 'Mooli', defaultQty: '500g' },
    { id: 5, name: 'Palak', defaultQty: '250g' },
    { id: 6, name: 'Phool Gobhi', defaultQty: '1' },
    { id: 7, name: 'Bhindi', defaultQty: '250g' },
    { id: 11, name: 'Gajar', defaultQty: '1kg' },
    { id: 12, name: 'Shalgam', defaultQty: '500g' },
    { id: 13, name: 'Baingan', defaultQty: '500g' },
    { id: 14, name: 'Matar', defaultQty: '1kg' },
    { id: 15, name: 'Patta Gobi', defaultQty: '1pc' },
    { id: 16, name: 'Lauki', defaultQty: '1pc' },
    { id: 17, name: 'Arbi', defaultQty: '250g' },
    { id: 19, name: 'Kaddu', defaultQty: '1pc' },
    { id: 20, name: 'Karela', defaultQty: '250g' },
    { id: 21, name: 'Methi', defaultQty: '250g' },
    { id: 23, name: 'Turai', defaultQty: '250g' },
    { id: 29, name: 'Barbati', defaultQty: '250g' },
    { id: 30, name: 'Shalgam', defaultQty: '500g' },
    { id: 8, name: 'Hari Mirch', defaultQty: '100g' },
    { id: 9, name: 'Dhaniya', defaultQty: '100g' },
    { id: 10, name: 'Adrak', defaultQty: '100g' },
];
